CLARRITY_THRESHOLD = 1200
ATTACK_SAMPLE_LIMIT = 1000
PERTURBATION_LIMIT = 1.0
BETA = 10

FILTER_SAMPLE_PATH = 'DeepFool_Atk_Filter.npz'
ATTACK_SAMPLE_PATH = 'DeepFool_Atks.npz'

FILTER_SAMPLE_PATH_CW2 = 'cw_2_Atk_Filter.npz'
ATTCK_SAMPLE_PATH_CW2 = 'cw_2_Atks.npz'

FILTER_SAMPLE_PATH_MIM = 'mim_Atk_Filter.npz'
ATTCK_SAMPLE_PATH_MIM = 'mim_Atks.npz'

FILTER_SAMPLE_PATH_BIM = 'bim_Atk_Filter.npz'
ATTCK_SAMPLE_PATH_BIM = 'bim_Atks.npz'